CREATE TABLE ITEM
(
    cod           BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    item_position BIGINT        NOT NULL,
    title         VARCHAR2(100) NOT NULL,
    price         NUMERIC(6, 2) NOT NULL,
    description   TEXT          NOT NULL
);

CREATE TABLE COLOR
(
    cod   BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    color varchar2(7) NOT NULL UNIQUE
);

CREATE TABLE ITEM_COLOR
(
    cod       BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    color_cod BIGINT REFERENCES COLOR NOT NULL,
    item_cod  BIGINT REFERENCES ITEM  NOT NULL,
    UNIQUE (color_cod, item_cod)
);

CREATE TABLE SIZE
(
    cod  BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    size VARCHAR2(3) NOT NULL UNIQUE
);

CREATE TABLE ITEM_SIZE
(
    cod      BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    size_cod BIGINT REFERENCES SIZE NOT NULL,
    item_cod BIGINT REFERENCES ITEM NOT NULL,
    UNIQUE (size_cod, item_cod)
);

CREATE TABLE ITEM_IMAGE
(
    cod       BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    url       TEXT                   NOT NULL,
    item_cod  BIGINT REFERENCES ITEM NOT NULL,
    color_cod BIGINT REFERENCES COLOR,
    UNIQUE (url, item_cod, color_cod)
)
