CREATE TABLE CART
(
    cod      BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    token char(36),
    user_cod BIGINT REFERENCES USERS
);

CREATE TABLE CART_ITEM
(
    COD       BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CART_COD  BIGINT REFERENCES CART NOT NULL,
    ITEM_COD  BIGINT REFERENCES ITEM NOT NULL,
    SIZE_COD  BIGINT REFERENCES SIZE,
    COLOR_COD BIGINT REFERENCES COLOR,
    QUANTITY  NUMERIC                NOT NULL,

    UNIQUE (CART_COD, ITEM_COD, SIZE_COD, COLOR_COD)
);
