CREATE TABLE RECIPIENT(
COD BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
USER_COD BIGINT REFERENCES USERS NOT NULL,
FIRSTNAME TEXT NOT NULL,
SURNAME TEXT,
EMAIL TEXT NOT NULL,
TELEPHONE TEXT NOT NULL,
STARRED BOOLEAN NOT NULL
);

CREATE TABLE BILLING_INFO(
COD BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
USER_COD BIGINT REFERENCES USERS  NOT NULL,
ENTITY_NAME TEXT NOT NULL,
EMAIL TEXT NOT NULL,
TAX_ID TEXT NOT NULL,
STARRED BOOLEAN NOT NULL
);



