CREATE TABLE PAYMENT_TRANSACTION(
COD BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
IDENTIFIER CHAR(36) NOT NULL UNIQUE ,
CREATED_AT TIMESTAMP NOT NULL,
STATUS VARCHAR(23) NOT NULL,
USER_COD  BIGINT REFERENCES USERS NOT NULL
);

CREATE TABLE PAYMENT_ELEMENT(
    COD       BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PAYMENT_TRANSACTION_COD  BIGINT REFERENCES PAYMENT_TRANSACTION NOT NULL,
    ITEM_COD  BIGINT REFERENCES ITEM NOT NULL,
    SIZE_COD  BIGINT REFERENCES SIZE,
    COLOR_COD BIGINT REFERENCES COLOR,
    QUANTITY  NUMERIC                NOT NULL,

    UNIQUE (PAYMENT_TRANSACTION_COD, ITEM_COD, SIZE_COD, COLOR_COD)
);
